10 year anniversary  (#1)
* happy 10 year anniversary!

- remove `bics avail`
- remove `bics search`
- colorize `bics help` and `bics init`
- make `bics help` more readable
- rename `bics upgrade` to `bics self-upgrade` to better distinguish it

* small touches

---------

Co-authored-by: Dave Eddy <deddy@fastly.com>

diff --git a/bics b/bics
--- a/bics
+++ b/bics
@@ -8,7 +8,7 @@
 # Date: 9/24/2013
 # License: MIT
 
-BICS_VERSION='v0.0.2'
+BICS_VERSION='v0.1.0'
 BICS_SOURCED=()
 
 # bics initialization function, called when bics is sourced
@@ -16,7 +16,7 @@ _() {
 	local f
 	for f in ~/.bics/plugins/*/*.bash; do
 		[[ -f $f ]] || continue
-		. "$f" && BICS_SOURCED=("${BICS_SOURCED[@]}" "${f/#$HOME\/.bics\/plugins\/}")
+		. "$f" && BICS_SOURCED+=("$f")
 	done
 }
 
@@ -28,13 +28,17 @@ _bics() {
 
 	case "$COMP_CWORD" in
 		1)
-			words=(init install remove list search available update upgrade version help);;
+			words=(
+				init install remove list
+				update self-upgrade version help
+			)
+			;;
 		*)
 			local installed=()
 			local f
 			for f in ~/.bics/plugins/*; do
 				[[ -d $f ]] || continue
-				installed=("${f##*/}" "${installed[@]}")
+				installed+=("${f##*/}")
 			done
 
 			case "$cmd" in
@@ -47,7 +51,9 @@ _bics() {
 
 	local _word
 	for _word in "${words[@]}"; do
-		[[ $_word == "$word"* || -z $word ]] && COMPREPLY=("${COMPREPLY[@]}" "$_word")
+		if [[ $_word == "$word"* || -z $word ]]; then
+			COMPREPLY+=("$_word")
+		fi
 	done
 }
 
@@ -61,73 +67,41 @@ if (return 2>/dev/null); then
 	return
 fi
 
-sourceurl='https://raw.githubusercontent.com/bahamas10/bics/master/bics'
-wikiurl='https://raw.githubusercontent.com/wiki/bahamas10/bics/Plugins.md'
+# if we are here then this script is being executed interactively
 
-# Limit the number of columns printed
-limitcolumns() {
-	if ! [[ -t 1 ]]; then
-		# do nothing if the output is not a tty
-		cat
-		return $?
-	fi
-	local red=$(tput setaf 1)
-	local reset=$(tput sgr0)
-	local cols=$1
-	cols=${cols:-$COLUMNS}
-	cols=${cols:-$(tput cols)}
-	cols=${cols:-80}
-	awk "
-	{
-		if (length(\$0) > $cols)
-			\$0 = substr(\$0, 0, $cols - 1) \"$red>$reset\";
-		print \$0
-	}"
-}
+SOURCE_URL='https://raw.githubusercontent.com/bahamas10/bics/master/bics'
 
 usage() {
+	local rst=$(tput sgr0 2>/dev/null)
+	local green=$(tput setaf 2 2>/dev/null)
+
 	cat <<-EOF
-	usage: bics [command] [args...]
-	($BICS_VERSION)
+	${green}bics$rst - Bash Interactive Configuration Management ($BICS_VERSION)
+	Usage: bics [command] [args...]
 
-	example
+	Subcommands:
+	    ${green}bics install <repo> [name]$rst
+	      install a bics plugin from a git repository
 
-	  bics init
-	    -- install bics on this system, typically called as the oneliner from the readme
+	    ${green}bics list$rst
+	      list installed bics plugins (in ~/.bics/plugins)
 
-	  bics install <repo> [name]
-	    -- install a bics plugin from a git repository
+	    ${green}bics remove <name> ...$rst
+	      remove a bics plugin
 
-	  bics remove <name> ...
-	    -- remove a bics plugin
+	    ${green}bics update [name]$rst
+	      update a bics plugin via \`git pull\`.  if 'name' is not given
+	      all plugins are updated
 
-	  bics list
-	    -- list installed plugins
+	    ${green}bics self-upgrade$rst
+	      update \`bics\` itself to the newest version from github
 
-	  bics search <name>
-	    -- search for plugins
+	    ${green}bics help [name]$rst
+	      show this message and exit.  if 'name' is given show that plugins
+	      readme in \`\$PAGER\`
 
-	  bics available
-	    -- show all avaliable bics plugins
-
-	  bics update [name]
-	    -- update 'name' via git pull on the local machine
-	    -- if 'name' is not given, all plugins are updated
-
-	  bics upgrade
-	    -- update bics to the newest version from github
-
-	  bics help [name]
-	    -- show this message and exit
-	    -- if 'name' is given, show that plugins readme in PAGER
-
-	  bics version
-	    -- print the version number of bics that is currently installed
-
-	plugins
-
-	  the official list of plugins used by 'search' and 'available'
-	  https://github.com/bahamas10/bics/wiki/Plugins
+	    ${green}bics version$rst
+	      print the version number of bics and exit
 	EOF
 }
 
@@ -140,23 +114,27 @@ list() {
 }
 
 init() {
+	local rst=$(tput sgr0 2>/dev/null)
+	local green=$(tput setaf 2 2>/dev/null)
+
 	if [[ ! -d ~/.bics ]]; then
 		mkdir -p ~/.bics/plugins/test-plugin
-		echo '> ~/.bics created'
+		echo "> ${green}~/.bics$rest created"
 
 		echo '# add code here' > ~/.bics/plugins/test-plugin/test-plugin.bash
 		echo 'this plugin does nothing' > ~/.bics/plugins/test-plugin/help.txt
 		echo '> test-plugin created'
 	fi
 
-	upgrade || return $?
+	self-upgrade || return $?
 
 	cat <<-EOF
 
-	= to get started =
-	1. add '. ~/.bics/bics' to your .bashrc to load plugins
-	2. run 'exec bash' to load bics
-	3. run 'bics list' to view installed plugins and 'bics available' to show avaliable packages
+	${green}bics$rst - Getting Started
+	1. add $green'. ~/.bics/bics'$rst to your \`.bashrc\` file
+	2. run ${green}exec bash$rst to reload your current shell
+	3. install plugins with ${green}bics install <repo>$rst
+	4. run ${green}bics list$rst to view installed plugins
 	EOF
 }
 
@@ -191,20 +169,12 @@ remove_() {
 	echo
 	local ans=n
 	if ! $yes; then
-		read -p '> are you sure? [y/N]: ' ans
+		read -r -p '> are you sure? [y/N]: ' ans
 		[[ $ans == y ]] || return 1
 	fi
 
 	cd ~/.bics/plugins || return $?
 	rm -r "$@"
-}
-
-
-search() {
-	curl -sS "$wikiurl" | \
-		awk '-F|' '$5 { printf("%15-s %-50s %-15s %-15s %s\n", $1, $3, $2, $4, $5) }' | \
-		grep -i "$1" | \
-		limitcolumns
 }
 
 update() {
@@ -232,17 +202,17 @@ update() {
 	return "$ret"
 }
 
-upgrade() {
-	echo -n "> getting source from $sourceurl... "
-	if curl -L -sS -o ~/.bics/bics.temp "$sourceurl"; then
-		mv ~/.bics/bics.temp ~/.bics/bics
-		chmod +x ~/.bics/bics
-		echo 'done'
-		echo "> bics $(~/.bics/bics -v) installed"
-	else
-		echo 'failed to fetch!!'
+self-upgrade() {
+	echo -n "> getting source from $SOURCE_URL... "
+	if ! curl -L -sS -o ~/.bics/bics.temp "$SOURCE_URL"; then
+		echo 'failed to fetch!!' >&2
 		return 1
 	fi
+
+	mv ~/.bics/bics.temp ~/.bics/bics
+	chmod +x ~/.bics/bics
+	echo 'done'
+	echo "> bics $(~/.bics/bics -v) installed"
 }
 
 help_() {
@@ -257,7 +227,7 @@ help_() {
 		d=~/.bics/plugins/$name
 		if [[ ! -d $d ]]; then
 			echo "> plugin $name not found" >&2
-			((ret++))
+			ret=1
 			continue
 		fi
 
@@ -270,7 +240,7 @@ help_() {
 
 		if [[ -z $file ]]; then
 			echo "> no documentation for $name found" >&2
-			((ret++))
+			ret=1
 			continue
 		fi
 
@@ -283,14 +253,12 @@ help_() {
 cmd=$1
 shift
 case "$cmd" in
-	available|avail) search "";;
 	init) init;;
 	in|install) install_ "$@";;
 	rm|remove) remove_ "$@";;
 	list|ls) list "$@";;
-	search|se|grep) search "$@";;
 	update|up) update "$@";;
-	upgrade|fug) upgrade "$@";;
+	self-upgrade|fug) self-upgrade "$@";;
 	-h|help) help_ "$@";;
 	-v|v|version) echo "$BICS_VERSION";;
 	*) usage >&2; exit 1;;
